#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.4 (swiftlang-6.4.0.34.1 clang-2100.3.34.1)
#ifndef FBCONTROLCORE_SWIFT_H
#define FBCONTROLCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Warc-bridge-casts-disallowed-in-nonarc"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBControlCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import Darwin;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
@import _DarwinFoundation2.sys_types;
#endif

#import <FBControlCore/FBControlCore.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Warc-bridge-casts-disallowed-in-nonarc"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBControlCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSNull;
/// Observation of a Data Consumer’s lifecycle.
SWIFT_PROTOCOL("_TtP13FBControlCore23FBDataConsumerLifecycle_")
@protocol FBDataConsumerLifecycle <NSObject>
/// A Future that resolves when there is no more data to write and any underlying resource managed by the consumer is released.
@property (nonatomic, readonly, strong) FBFuture<NSNull *> * _Nonnull finishedConsuming;
@end

@class NSData;
/// A consumer of NSData.
SWIFT_PROTOCOL("_TtP13FBControlCore14FBDataConsumer_")
@protocol FBDataConsumer <NSObject>
/// Consumes the provided binary data.
- (void)consumeData:(NSData * _Nonnull)data;
/// Consumes an end-of-file.
- (void)consumeEndOfFile;
@end

@class NSString;
/// The non-mutating methods of a buffer.
SWIFT_PROTOCOL("_TtP13FBControlCore20FBAccumulatingBuffer_")
@protocol FBAccumulatingBuffer <FBDataConsumer, FBDataConsumerLifecycle>
/// Obtains a copy of the current output data.
- (NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// The current output split on newlines.
- (NSArray<NSString *> * _Nonnull)lines SWIFT_WARN_UNUSED_RESULT;
@end

/// How an application came to be installed.
typedef SWIFT_ENUM(NSUInteger, FBApplicationInstallType, open) {
/// The Application is unknown.
  FBApplicationInstallTypeUnknown = 0,
/// The Application is part of the Operating System.
  FBApplicationInstallTypeSystem = 1,
/// The Application is part of macOS.
  FBApplicationInstallTypeMac = 2,
/// The Application has been installed by the user.
  FBApplicationInstallTypeUser = 3,
/// The Application has been installed by the user and signed with a distribution certificate.
  FBApplicationInstallTypeUserEnterprise = 4,
/// The Application has been installed by the user and signed with a development certificate.
  FBApplicationInstallTypeUserDevelopment = 5,
};

SWIFT_CLASS_NAMED("FBProcessLaunchConfiguration")
@interface FBProcessLaunchConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull arguments;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull environment;
@property (nonatomic, readonly, strong) FBProcessIO<id, id, id> * _Nonnull io;
- (nonnull instancetype)initWithArguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBApplicationLaunchConfiguration")
@interface FBApplicationLaunchConfiguration : FBProcessLaunchConfiguration
@property (nonatomic, readonly, copy) NSString * _Nonnull bundleID;
@property (nonatomic, readonly, copy) NSString * _Nullable bundleName;
@property (nonatomic, readonly) BOOL waitForDebugger;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)initWithArguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS_NAMED("FBCollectionInformation")
@interface FBCollectionInformation : NSObject
+ (NSString * _Nonnull)oneLineDescriptionFromArray:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)oneLineDescriptionFromArray:(NSArray * _Nonnull)array atKeyPath:(NSString * _Nonnull)keyPath SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)oneLineDescriptionFromDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isArrayHeterogeneous:(NSArray * _Nonnull)array withClass:(Class _Nonnull)cls SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isDictionaryHeterogeneous:(NSDictionary * _Nonnull)dictionary keyClass:(Class _Nonnull)keyCls valueClass:(Class _Nonnull)valueCls SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSIndexSet;
@class NSNumber;
@protocol NSCopying;
SWIFT_CLASS_NAMED("FBCollectionOperations")
@interface FBCollectionOperations : NSObject
+ (NSArray<NSNumber *> * _Nonnull)arrayFromIndices:(NSIndexSet * _Nonnull)indices SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, id> * _Nonnull)recursiveFilteredJSONSerializableRepresentationOfDictionary:(NSDictionary<NSString *, id> * _Nonnull)input SWIFT_WARN_UNUSED_RESULT;
+ (NSArray * _Nonnull)recursiveFilteredJSONSerializableRepresentationOfArray:(NSArray * _Nonnull)input SWIFT_WARN_UNUSED_RESULT;
+ (NSIndexSet * _Nonnull)indicesFromArray:(NSArray<NSNumber *> * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)nullableValueForDictionary:(NSDictionary * _Nonnull)dictionary key:(id <NSCopying> _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (NSArray * _Nonnull)arrayWithObject:(id _Nonnull)object count:(NSUInteger)count SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface FBCompositeDataConsumer (SWIFT_EXTENSION(FBControlCore)) <FBDataConsumer, FBDataConsumerLifecycle>
@end

/// Receives log messages. Conformers must be thread-safe: loggers are shared across queues,
/// private-framework callback threads and actors.
SWIFT_PROTOCOL("_TtP13FBControlCore19FBControlCoreLogger_")
@protocol FBControlCoreLogger <NSObject>
/// Logs a Message with the provided String.
- (id <FBControlCoreLogger> _Nonnull)log:(NSString * _Nonnull)message;
/// Returns the Info Logger variant.
- (id <FBControlCoreLogger> _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
/// Returns the Debug Logger variant.
- (id <FBControlCoreLogger> _Nonnull)debug SWIFT_WARN_UNUSED_RESULT;
/// Returns the Error Logger variant.
- (id <FBControlCoreLogger> _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
/// Returns a Logger for a named ‘facility’ or ‘tag’.
- (id <FBControlCoreLogger> _Nonnull)withName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Enables or Disables date formatting in the logger.
- (id <FBControlCoreLogger> _Nonnull)withDateFormatEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
/// The Prefix for the Logger, if set.
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// The Current Log Level.
@property (nonatomic, readonly) FBControlCoreLogLevel level;
@end

@interface FBCompositeLogger (SWIFT_EXTENSION(FBControlCore)) <FBControlCoreLogger>
@end

@class NSDate;
@class NSError;
SWIFT_PROTOCOL_NAMED("FBCrashLogParser")
@protocol FBCrashLogParser <NSObject>
- (void)parseCrashLogFromString:(NSString * _Nonnull)str executablePathOut:(NSString * _Nonnull * _Nonnull)executablePathOut identifierOut:(NSString * _Nonnull * _Nonnull)identifierOut processNameOut:(NSString * _Nonnull * _Nonnull)processNameOut parentProcessNameOut:(NSString * _Nonnull * _Nonnull)parentProcessNameOut processIdentifierOut:(pid_t * _Nonnull)processIdentifierOut parentProcessIdentifierOut:(pid_t * _Nonnull)parentProcessIdentifierOut dateOut:(NSDate * _Nonnull * _Nonnull)dateOut exceptionDescription:(NSString * _Nonnull * _Nonnull)exceptionDescription crashedThreadDescription:(NSString * _Nonnull * _Nonnull)crashedThreadDescription error:(NSError * _Nullable * _Nullable)error;
@end

/// A macOS 12+ <code>.ips</code> file is two concatenated JSON objects (metadata, then content) with some fields
/// repeated. Apple can change the layout, so every object is searched for each needed field rather
/// than assuming a position.
SWIFT_CLASS("_TtC13FBControlCore28FBConcatedJSONCrashLogParser")
@interface FBConcatedJSONCrashLogParser : NSObject <FBCrashLogParser>
- (void)parseCrashLogFromString:(NSString * _Nonnull)str executablePathOut:(NSString * _Nonnull * _Nonnull)executablePathOut identifierOut:(NSString * _Nonnull * _Nonnull)identifierOut processNameOut:(NSString * _Nonnull * _Nonnull)processNameOut parentProcessNameOut:(NSString * _Nonnull * _Nonnull)parentProcessNameOut processIdentifierOut:(pid_t * _Nonnull)processIdentifierOut parentProcessIdentifierOut:(pid_t * _Nonnull)parentProcessIdentifierOut dateOut:(NSDate * _Nonnull * _Nonnull)dateOut exceptionDescription:(NSString * _Nonnull * _Nonnull)exceptionDescription crashedThreadDescription:(NSString * _Nonnull * _Nonnull)crashedThreadDescription error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The mutating methods of a buffer. All methods are fully synchronized.
SWIFT_PROTOCOL("_TtP13FBControlCore18FBConsumableBuffer_")
@protocol FBConsumableBuffer <FBAccumulatingBuffer>
/// Consume the remainder of the buffer available, returning it as Data.
- (NSData * _Nonnull)consumeCurrentData SWIFT_WARN_UNUSED_RESULT;
/// Consume the remainder of the buffer available, returning it as a String.
- (NSString * _Nullable)consumeCurrentString SWIFT_WARN_UNUSED_RESULT;
/// Consumes an amount of data from the buffer.
- (NSData * _Nullable)consumeLength:(NSUInteger)length SWIFT_WARN_UNUSED_RESULT;
/// Removes and returns the bytes before the first <code>terminal</code> (dropping the terminal), or nil if absent.
- (NSData * _Nullable)consumeUntil:(NSData * _Nonnull)terminal SWIFT_WARN_UNUSED_RESULT;
/// Consume a line if one is available, returning it as Data.
- (NSData * _Nullable)consumeLineData SWIFT_WARN_UNUSED_RESULT;
/// Consume a line if one is available, returning it as a String.
- (NSString * _Nullable)consumeLineString SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC13FBControlCore18FBControlCoreError")
@interface FBControlCoreError : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)describe:(NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)describe:(NSString * _Nonnull)description;
+ (nonnull instancetype)causedBy:(NSError * _Nullable)cause SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)causedBy:(NSError * _Nullable)cause;
- (BOOL)failBool:(NSError * _Nullable * _Nullable)error;
- (int32_t)failInt:(NSError * _Nullable * _Nullable)error;
- (uint32_t)failUInt:(NSError * _Nullable * _Nullable)error;
- (CGRect)failRect:(NSError * _Nullable * _Nullable)error;
- (id _Nullable)fail:(NSError * _Nullable * _Nullable)error;
- (FBFuture<id> * _Nonnull)failFuture SWIFT_WARN_UNUSED_RESULT;
- (void * _Nullable)failPointer:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)extraInfo:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (nonnull instancetype)recursiveDescription;
- (nonnull instancetype)noRecursiveDescription;
- (nonnull instancetype)inDomain:(NSString * _Nonnull)domain;
- (nonnull instancetype)code:(NSInteger)code;
- (NSError * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface FBControlCoreError (SWIFT_EXTENSION(FBControlCore))
+ (NSError * _Nonnull)errorForDescription:(NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)failWithErrorMessage:(NSString * _Nonnull)errorMessage errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)failWithError:(NSError * _Nonnull)failureCause errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)failWithError:(NSError * _Nonnull)failureCause description:(NSString * _Nonnull)description errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)failBoolWithErrorMessage:(NSString * _Nonnull)errorMessage errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)failBoolWithError:(NSError * _Nonnull)failureCause errorOut:(NSError * _Nullable * _Nullable)errorOut;
+ (BOOL)failBoolWithError:(NSError * _Nonnull)failureCause description:(NSString * _Nonnull)description errorOut:(NSError * _Nullable * _Nullable)errorOut;
+ (FBFuture<id> * _Nonnull)failFutureWithError:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("FBControlCoreGlobalConfiguration")
@interface FBControlCoreGlobalConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval fastTimeout;)
+ (NSTimeInterval)fastTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval regularTimeout;)
+ (NSTimeInterval)regularTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval slowTimeout;)
+ (NSTimeInterval)slowTimeout SWIFT_WARN_UNUSED_RESULT;
/// The logger used wherever a nullable logger parameter is passed as nil.
/// By default it writes only to os_log (subsystem <code>com.facebook.fbcontrolcore</code>) at info level, so
/// in a process without a terminal nothing reaches stderr and diagnostics are only visible via
/// <code>log stream --predicate 'subsystem == "com.facebook.fbcontrolcore"'</code>.
/// <code>FBCONTROLCORE_LOGGING</code> mirrors output to stderr; <code>FBCONTROLCORE_DEBUG_LOGGING</code> raises the level to debug.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id <FBControlCoreLogger> _Nonnull defaultLogger;)
+ (id <FBControlCoreLogger> _Nonnull)defaultLogger SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultLogger:(id <FBControlCoreLogger> _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL confirmCodesignaturesAreValid;)
+ (BOOL)confirmCodesignaturesAreValid SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Internal forwarding protocol used by FBDataBuffer implementations.
SWIFT_PROTOCOL("_TtP13FBControlCore22FBDataBuffer_Forwarder_")
@protocol FBDataBuffer_Forwarder <NSObject>
- (void)run:(id <FBConsumableBuffer> _Nonnull)buffer;
@property (nonatomic, readonly, strong) id <FBDataConsumer> _Nonnull consumer;
@end

/// Consumer which consumes the data asynchronously.
SWIFT_PROTOCOL("_TtP13FBControlCore19FBDataConsumerAsync_")
@protocol FBDataConsumerAsync <NSObject>
/// Number of submitted data that has not been consumed yet.
- (NSInteger)unprocessedDataCount SWIFT_WARN_UNUSED_RESULT;
@end

/// Consumer which consumes the data synchronously in the same context as the caller invoking consumeData.
SWIFT_PROTOCOL("_TtP13FBControlCore18FBDataConsumerSync_")
@protocol FBDataConsumerSync <NSObject>
@end

SWIFT_CLASS("_TtC13FBControlCore19FBDataDownloadInput")
@interface FBDataDownloadInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSURLSessionTask;
@interface FBDataDownloadInput (SWIFT_EXTENSION(FBControlCore)) <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
@end

/// A consumer of dispatch_data.
SWIFT_PROTOCOL("_TtP13FBControlCore22FBDispatchDataConsumer_")
@protocol FBDispatchDataConsumer <NSObject>
/// Consumes the provided binary data.
- (void)consumeData:(dispatch_data_t _Nonnull)data;
/// Consumes an end-of-file.
- (void)consumeEndOfFile;
@end

/// A Protocol for defining file reading.
SWIFT_PROTOCOL("_TtP13FBControlCore20FBFileReaderProtocol_")
@protocol FBFileReaderProtocol
/// Starts reading the file.
- (FBFuture<NSNull *> * _Nonnull)startReading;
/// Stops reading the file.
- (FBFuture<NSNumber *> * _Nonnull)stopReading;
/// Waits for the reader to finish reading, backing off to stopping in the event of a timeout.
- (FBFuture<NSNumber *> * _Nonnull)finishedReadingWithTimeout:(NSTimeInterval)timeout;
/// The current state of the file reader.
@property (nonatomic, readonly) FBFileReaderState state;
/// A Future that resolves when the reading of the file handle has no pending operations on the file descriptor.
@property (nonatomic, readonly, strong) FBFuture<NSNumber *> * _Nonnull finishedReading;
@end

SWIFT_CLASS_NAMED("FBFileReader")
@interface FBFileReader : NSObject <FBFileReaderProtocol>
@property (nonatomic, readonly) FBFileReaderState state;
+ (nonnull instancetype)readerWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile consumer:(id <FBDataConsumer> _Nonnull)consumer logger:(id <FBControlCoreLogger> _Nullable)logger SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)dispatchDataReaderWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile consumer:(id <FBDispatchDataConsumer> _Nonnull)consumer logger:(id <FBControlCoreLogger> _Nullable)logger SWIFT_WARN_UNUSED_RESULT;
+ (FBFuture<FBFileReader *> * _Nonnull)readerWithFilePath:(NSString * _Nonnull)filePath consumer:(id <FBDataConsumer> _Nonnull)consumer logger:(id <FBControlCoreLogger> _Nullable)logger SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (FBFuture<NSNull *> * _Nonnull)startReading SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNumber *> * _Nonnull)stopReading SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNumber *> * _Nonnull)finishedReadingWithTimeout:(NSTimeInterval)timeout SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) FBFuture<NSNumber *> * _Nonnull finishedReading;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBFileWriter")
@interface FBFileWriter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <FBDataConsumer> _Nonnull nullWriter;)
+ (id <FBDataConsumer> _Nonnull)nullWriter SWIFT_WARN_UNUSED_RESULT;
+ (FBFuture<id> * _Nonnull)asyncDispatchDataWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nonnull)syncWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nullable)asyncWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile queue:(dispatch_queue_t _Nonnull)queue error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nullable)asyncWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nullable)syncWriterForFilePath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (FBFuture<id> * _Nonnull)asyncWriterForFilePath:(NSString * _Nonnull)filePath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface FBLoggingDataConsumer (SWIFT_EXTENSION(FBControlCore)) <FBDataConsumer>
@end

/// A Consumable buffer that also allows forwarding and notifying.
SWIFT_PROTOCOL("_TtP13FBControlCore17FBNotifyingBuffer_")
@protocol FBNotifyingBuffer <FBConsumableBuffer>
/// Forwards to another data consumer, notifying every time a terminal is passed.
- (BOOL)consume:(id <FBDataConsumer> _Nonnull)consumer onQueue:(dispatch_queue_t _Nullable)queue untilTerminal:(NSData * _Nonnull)terminal error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Notifies when there has been consumption to a terminal.
- (FBFuture<NSData *> * _Nonnull)consumeAndNotifyWhen:(NSData * _Nonnull)terminal SWIFT_WARN_UNUSED_RESULT;
/// Consumes based upon a fixed-length header, that can be parsed.
- (FBFuture<NSData *> * _Nonnull)consumeHeaderLength:(NSUInteger)headerLength derivedLength:(NSUInteger (^ _Nonnull)(NSData * _Nonnull))derivedLength SWIFT_WARN_UNUSED_RESULT;
@end

@interface FBNullDataConsumer (SWIFT_EXTENSION(FBControlCore)) <FBDataConsumer>
@end

/// Parses the pre-macOS 12 plain-text <code>.crash</code> format.
SWIFT_CLASS("_TtC13FBControlCore25FBPlainTextCrashLogParser")
@interface FBPlainTextCrashLogParser : NSObject <FBCrashLogParser>
- (void)parseCrashLogFromString:(NSString * _Nonnull)str executablePathOut:(NSString * _Nonnull * _Nonnull)executablePathOut identifierOut:(NSString * _Nonnull * _Nonnull)identifierOut processNameOut:(NSString * _Nonnull * _Nonnull)processNameOut parentProcessNameOut:(NSString * _Nonnull * _Nonnull)parentProcessNameOut processIdentifierOut:(pid_t * _Nonnull)processIdentifierOut parentProcessIdentifierOut:(pid_t * _Nonnull)parentProcessIdentifierOut dateOut:(NSDate * _Nonnull * _Nonnull)dateOut exceptionDescription:(NSString * _Nonnull * _Nonnull)exceptionDescription crashedThreadDescription:(NSString * _Nonnull * _Nonnull)crashedThreadDescription error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Process Output that can be provided through a file.
SWIFT_PROTOCOL("_TtP13FBControlCore19FBProcessFileOutput_")
@protocol FBProcessFileOutput <NSObject>
/// The File Path to write to.
@property (nonatomic, readonly, copy) NSString * _Nonnull filePath;
/// Should be called just after the file path has been written to.
- (FBFuture<NSNull *> * _Nonnull)startReading SWIFT_WARN_UNUSED_RESULT;
/// Should be called just after the file has stopped being written to.
- (FBFuture<NSNull *> * _Nonnull)stopReading SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("FBProcessInfo")
@interface FBProcessInfo : NSObject <NSCopying>
@property (nonatomic, readonly) pid_t processIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull launchPath;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull arguments;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull environment;
@property (nonatomic, readonly, copy) NSString * _Nonnull processName;
- (nonnull instancetype)initWithProcessIdentifier:(pid_t)processIdentifier launchPath:(NSString * _Nonnull)launchPath arguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBProcessStreamAttachment;
/// A Protocol that wraps the standard stream stdout, stderr, stdin.
SWIFT_PROTOCOL("_TtP13FBControlCore16FBStandardStream_")
@protocol FBStandardStream <NSObject>
/// Attaches to the output, returning an FBProcessStreamAttachment.
- (FBFuture<FBProcessStreamAttachment *> * _Nonnull)attach SWIFT_WARN_UNUSED_RESULT;
/// Tears down the output.
- (FBFuture<NSNull *> * _Nonnull)detach SWIFT_WARN_UNUSED_RESULT;
@end

@interface FBProcessInput<WrappedType> (SWIFT_EXTENSION(FBControlCore)) <FBStandardStream>
@end

/// Process output that can be redirected to a file path or to a data consumer.
SWIFT_PROTOCOL_NAMED("FBProcessOutputProtocol")
@protocol FBProcessOutput <NSObject>
/// Allows the receiver to be written to via a file instead of via a file handle.
- (FBFuture<id <FBProcessFileOutput>> * _Nonnull)providedThroughFile SWIFT_WARN_UNUSED_RESULT;
/// Allows the receiver to be written to via a Data Consumer.
- (FBFuture<id <FBDataConsumer>> * _Nonnull)providedThroughConsumer SWIFT_WARN_UNUSED_RESULT;
@end

@interface FBProcessOutput<WrappedType> (SWIFT_EXTENSION(FBControlCore)) <FBProcessOutput, FBStandardStream>
@end

@class FBProcessIOAttachment;
@class FBProcessSpawnConfiguration;
SWIFT_CLASS_NAMED("FBProcessSpawnCommandHelpers")
@interface FBProcessSpawnCommandHelpers : NSObject
+ (void)resolveProcessFinishedWithStatLoc:(int32_t)statLoc inTeardownOfIOAttachment:(FBProcessIOAttachment * _Nonnull)attachment statLocFuture:(FBMutableFuture<NSNumber *> * _Nonnull)statLocFuture exitCodeFuture:(FBMutableFuture<NSNumber *> * _Nonnull)exitCodeFuture signalFuture:(FBMutableFuture<NSNumber *> * _Nonnull)signalFuture processIdentifier:(pid_t)processIdentifier configuration:(FBProcessSpawnConfiguration * _Nonnull)configuration queue:(dispatch_queue_t _Nonnull)queue logger:(id <FBControlCoreLogger> _Nullable)logger;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_ENUM_FWD_DECL(NSUInteger, FBProcessSpawnMode)
SWIFT_CLASS_NAMED("FBProcessSpawnConfiguration")
@interface FBProcessSpawnConfiguration : FBProcessLaunchConfiguration
@property (nonatomic, readonly, copy) NSString * _Nonnull launchPath;
@property (nonatomic, readonly) enum FBProcessSpawnMode mode;
@property (nonatomic, readonly, copy) NSString * _Nonnull processName;
- (nonnull instancetype)initWithLaunchPath:(NSString * _Nonnull)launchPath arguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io mode:(enum FBProcessSpawnMode)mode OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)initWithArguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM_NAMED(NSUInteger, FBProcessSpawnMode, "FBProcessSpawnMode", open) {
  FBProcessSpawnModeDefault = 0,
  FBProcessSpawnModePosixSpawn = 1,
  FBProcessSpawnModeLaunchd = 2,
};

@class FBSocketServer;
/// The Delegate for the Server.
SWIFT_PROTOCOL("_TtP13FBControlCore22FBSocketServerDelegate_")
@protocol FBSocketServerDelegate <NSObject>
/// Called when the socket server has a new client connected.
/// The File Descriptor will not be automatically be closed, so it’s up to implementors to ensure that this happens so file descriptors do not leak.
/// If you wish to reject the connection, close the file handle immediately.
/// \param server the socket server.
///
/// \param address the IP Address of the connected client.
///
/// \param fileDescriptor the file descriptor of the connected socket.
///
- (void)socketServer:(FBSocketServer * _Nonnull)server clientConnected:(struct in6_addr)address fileDescriptor:(int32_t)fileDescriptor;
/// The Queue on which the Delegate will be called.
/// This may be a serial or a concurrent queue.
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull queue;
@end

/// Provides information about the state of a stream.
SWIFT_PROTOCOL("_TtP13FBControlCore24FBStandardStreamTransfer_")
@protocol FBStandardStreamTransfer <NSObject>
/// The number of bytes transferred.
@property (nonatomic, readonly) NSInteger bytesTransferred;
/// An error, if any has occurred in the streaming of data to the input.
@property (nonatomic, readonly) NSError * _Nullable streamError;
@end

@class AVCaptureFileOutput;
@class NSURL;
@class AVCaptureConnection;
SWIFT_CLASS("_TtC13FBControlCore17FBVideoFileWriter")
@interface FBVideoFileWriter : NSObject <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didStartRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didPauseRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output willFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didResumeRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBWeakFramework")
@interface FBWeakFramework : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
+ (FBWeakFramework * _Nonnull)xcodeFrameworkWithRelativePath:(NSString * _Nonnull)relativePath requiredClassNames:(NSArray<NSString *> * _Nonnull)requiredClassNames SWIFT_WARN_UNUSED_RESULT;
+ (FBWeakFramework * _Nonnull)frameworkWithPath:(NSString * _Nonnull)absolutePath requiredClassNames:(NSArray<NSString *> * _Nonnull)requiredClassNames rootPermitted:(BOOL)rootPermitted SWIFT_WARN_UNUSED_RESULT;
/// A nil logger loads silently.
- (BOOL)loadWithLogger:(id <FBControlCoreLogger> _Nullable)logger error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface FBWeakFramework (SWIFT_EXTENSION(FBControlCore))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull CoreSimulator;)
+ (FBWeakFramework * _Nonnull)CoreSimulator SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull SimulatorKit;)
+ (FBWeakFramework * _Nonnull)SimulatorKit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull DTXConnectionServices;)
+ (FBWeakFramework * _Nonnull)DTXConnectionServices SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull XCTDaemonControl;)
+ (FBWeakFramework * _Nonnull)XCTDaemonControl SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull XCUIAutomation;)
+ (FBWeakFramework * _Nonnull)XCUIAutomation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull XCTest;)
+ (FBWeakFramework * _Nonnull)XCTest SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull MobileDevice;)
+ (FBWeakFramework * _Nonnull)MobileDevice SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull AccessibilityPlatformTranslation;)
+ (FBWeakFramework * _Nonnull)AccessibilityPlatformTranslation SWIFT_WARN_UNUSED_RESULT;
@end

@class NSDecimalNumber;
@class NSNumberFormatter;
SWIFT_CLASS_NAMED("FBXcodeConfiguration")
@interface FBXcodeConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull developerDirectory;)
+ (NSString * _Nonnull)developerDirectory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull contentsDirectory;)
+ (NSString * _Nonnull)contentsDirectory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDecimalNumber * _Nonnull xcodeVersionNumber;)
+ (NSDecimalNumber * _Nonnull)xcodeVersionNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSOperatingSystemVersion xcodeVersion;)
+ (NSOperatingSystemVersion)xcodeVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDecimalNumber * _Nonnull iosSDKVersionNumber;)
+ (NSDecimalNumber * _Nonnull)iosSDKVersionNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSNumberFormatter * _Nonnull iosSDKVersionNumberFormatter;)
+ (NSNumberFormatter * _Nonnull)iosSDKVersionNumberFormatter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull iosSDKVersion;)
+ (NSString * _Nonnull)iosSDKVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isXcode12OrGreater;)
+ (BOOL)isXcode12OrGreater SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isXcode12_5OrGreater;)
+ (BOOL)isXcode12_5OrGreater SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("FBiOSTargetConfiguration")
@interface FBiOSTargetConfiguration : NSObject
+ (NSSet<FBArchitecture> * _Nonnull)baseArchsToCompatibleArch:(NSArray<FBArchitecture> * _Nonnull)architectures SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSPredicate (SWIFT_EXTENSION(FBControlCore))
+ (NSPredicate * _Nonnull)notNullPredicate SWIFT_WARN_UNUSED_RESULT;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.4 (swiftlang-6.4.0.34.1 clang-2100.3.34.1)
#ifndef FBCONTROLCORE_SWIFT_H
#define FBCONTROLCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Warc-bridge-casts-disallowed-in-nonarc"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBControlCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import Darwin;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
@import _DarwinFoundation2.sys_types;
#endif

#import <FBControlCore/FBControlCore.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Warc-bridge-casts-disallowed-in-nonarc"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBControlCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSNull;
/// Observation of a Data Consumer’s lifecycle.
SWIFT_PROTOCOL("_TtP13FBControlCore23FBDataConsumerLifecycle_")
@protocol FBDataConsumerLifecycle <NSObject>
/// A Future that resolves when there is no more data to write and any underlying resource managed by the consumer is released.
@property (nonatomic, readonly, strong) FBFuture<NSNull *> * _Nonnull finishedConsuming;
@end

@class NSData;
/// A consumer of NSData.
SWIFT_PROTOCOL("_TtP13FBControlCore14FBDataConsumer_")
@protocol FBDataConsumer <NSObject>
/// Consumes the provided binary data.
- (void)consumeData:(NSData * _Nonnull)data;
/// Consumes an end-of-file.
- (void)consumeEndOfFile;
@end

@class NSString;
/// The non-mutating methods of a buffer.
SWIFT_PROTOCOL("_TtP13FBControlCore20FBAccumulatingBuffer_")
@protocol FBAccumulatingBuffer <FBDataConsumer, FBDataConsumerLifecycle>
/// Obtains a copy of the current output data.
- (NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// The current output split on newlines.
- (NSArray<NSString *> * _Nonnull)lines SWIFT_WARN_UNUSED_RESULT;
@end

/// How an application came to be installed.
typedef SWIFT_ENUM(NSUInteger, FBApplicationInstallType, open) {
/// The Application is unknown.
  FBApplicationInstallTypeUnknown = 0,
/// The Application is part of the Operating System.
  FBApplicationInstallTypeSystem = 1,
/// The Application is part of macOS.
  FBApplicationInstallTypeMac = 2,
/// The Application has been installed by the user.
  FBApplicationInstallTypeUser = 3,
/// The Application has been installed by the user and signed with a distribution certificate.
  FBApplicationInstallTypeUserEnterprise = 4,
/// The Application has been installed by the user and signed with a development certificate.
  FBApplicationInstallTypeUserDevelopment = 5,
};

SWIFT_CLASS_NAMED("FBProcessLaunchConfiguration")
@interface FBProcessLaunchConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull arguments;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull environment;
@property (nonatomic, readonly, strong) FBProcessIO<id, id, id> * _Nonnull io;
- (nonnull instancetype)initWithArguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBApplicationLaunchConfiguration")
@interface FBApplicationLaunchConfiguration : FBProcessLaunchConfiguration
@property (nonatomic, readonly, copy) NSString * _Nonnull bundleID;
@property (nonatomic, readonly, copy) NSString * _Nullable bundleName;
@property (nonatomic, readonly) BOOL waitForDebugger;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)initWithArguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS_NAMED("FBCollectionInformation")
@interface FBCollectionInformation : NSObject
+ (NSString * _Nonnull)oneLineDescriptionFromArray:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)oneLineDescriptionFromArray:(NSArray * _Nonnull)array atKeyPath:(NSString * _Nonnull)keyPath SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)oneLineDescriptionFromDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isArrayHeterogeneous:(NSArray * _Nonnull)array withClass:(Class _Nonnull)cls SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isDictionaryHeterogeneous:(NSDictionary * _Nonnull)dictionary keyClass:(Class _Nonnull)keyCls valueClass:(Class _Nonnull)valueCls SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSIndexSet;
@class NSNumber;
@protocol NSCopying;
SWIFT_CLASS_NAMED("FBCollectionOperations")
@interface FBCollectionOperations : NSObject
+ (NSArray<NSNumber *> * _Nonnull)arrayFromIndices:(NSIndexSet * _Nonnull)indices SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, id> * _Nonnull)recursiveFilteredJSONSerializableRepresentationOfDictionary:(NSDictionary<NSString *, id> * _Nonnull)input SWIFT_WARN_UNUSED_RESULT;
+ (NSArray * _Nonnull)recursiveFilteredJSONSerializableRepresentationOfArray:(NSArray * _Nonnull)input SWIFT_WARN_UNUSED_RESULT;
+ (NSIndexSet * _Nonnull)indicesFromArray:(NSArray<NSNumber *> * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)nullableValueForDictionary:(NSDictionary * _Nonnull)dictionary key:(id <NSCopying> _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (NSArray * _Nonnull)arrayWithObject:(id _Nonnull)object count:(NSUInteger)count SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface FBCompositeDataConsumer (SWIFT_EXTENSION(FBControlCore)) <FBDataConsumer, FBDataConsumerLifecycle>
@end

/// Receives log messages. Conformers must be thread-safe: loggers are shared across queues,
/// private-framework callback threads and actors.
SWIFT_PROTOCOL("_TtP13FBControlCore19FBControlCoreLogger_")
@protocol FBControlCoreLogger <NSObject>
/// Logs a Message with the provided String.
- (id <FBControlCoreLogger> _Nonnull)log:(NSString * _Nonnull)message;
/// Returns the Info Logger variant.
- (id <FBControlCoreLogger> _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
/// Returns the Debug Logger variant.
- (id <FBControlCoreLogger> _Nonnull)debug SWIFT_WARN_UNUSED_RESULT;
/// Returns the Error Logger variant.
- (id <FBControlCoreLogger> _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
/// Returns a Logger for a named ‘facility’ or ‘tag’.
- (id <FBControlCoreLogger> _Nonnull)withName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Enables or Disables date formatting in the logger.
- (id <FBControlCoreLogger> _Nonnull)withDateFormatEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
/// The Prefix for the Logger, if set.
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// The Current Log Level.
@property (nonatomic, readonly) FBControlCoreLogLevel level;
@end

@interface FBCompositeLogger (SWIFT_EXTENSION(FBControlCore)) <FBControlCoreLogger>
@end

@class NSDate;
@class NSError;
SWIFT_PROTOCOL_NAMED("FBCrashLogParser")
@protocol FBCrashLogParser <NSObject>
- (void)parseCrashLogFromString:(NSString * _Nonnull)str executablePathOut:(NSString * _Nonnull * _Nonnull)executablePathOut identifierOut:(NSString * _Nonnull * _Nonnull)identifierOut processNameOut:(NSString * _Nonnull * _Nonnull)processNameOut parentProcessNameOut:(NSString * _Nonnull * _Nonnull)parentProcessNameOut processIdentifierOut:(pid_t * _Nonnull)processIdentifierOut parentProcessIdentifierOut:(pid_t * _Nonnull)parentProcessIdentifierOut dateOut:(NSDate * _Nonnull * _Nonnull)dateOut exceptionDescription:(NSString * _Nonnull * _Nonnull)exceptionDescription crashedThreadDescription:(NSString * _Nonnull * _Nonnull)crashedThreadDescription error:(NSError * _Nullable * _Nullable)error;
@end

/// A macOS 12+ <code>.ips</code> file is two concatenated JSON objects (metadata, then content) with some fields
/// repeated. Apple can change the layout, so every object is searched for each needed field rather
/// than assuming a position.
SWIFT_CLASS("_TtC13FBControlCore28FBConcatedJSONCrashLogParser")
@interface FBConcatedJSONCrashLogParser : NSObject <FBCrashLogParser>
- (void)parseCrashLogFromString:(NSString * _Nonnull)str executablePathOut:(NSString * _Nonnull * _Nonnull)executablePathOut identifierOut:(NSString * _Nonnull * _Nonnull)identifierOut processNameOut:(NSString * _Nonnull * _Nonnull)processNameOut parentProcessNameOut:(NSString * _Nonnull * _Nonnull)parentProcessNameOut processIdentifierOut:(pid_t * _Nonnull)processIdentifierOut parentProcessIdentifierOut:(pid_t * _Nonnull)parentProcessIdentifierOut dateOut:(NSDate * _Nonnull * _Nonnull)dateOut exceptionDescription:(NSString * _Nonnull * _Nonnull)exceptionDescription crashedThreadDescription:(NSString * _Nonnull * _Nonnull)crashedThreadDescription error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The mutating methods of a buffer. All methods are fully synchronized.
SWIFT_PROTOCOL("_TtP13FBControlCore18FBConsumableBuffer_")
@protocol FBConsumableBuffer <FBAccumulatingBuffer>
/// Consume the remainder of the buffer available, returning it as Data.
- (NSData * _Nonnull)consumeCurrentData SWIFT_WARN_UNUSED_RESULT;
/// Consume the remainder of the buffer available, returning it as a String.
- (NSString * _Nullable)consumeCurrentString SWIFT_WARN_UNUSED_RESULT;
/// Consumes an amount of data from the buffer.
- (NSData * _Nullable)consumeLength:(NSUInteger)length SWIFT_WARN_UNUSED_RESULT;
/// Removes and returns the bytes before the first <code>terminal</code> (dropping the terminal), or nil if absent.
- (NSData * _Nullable)consumeUntil:(NSData * _Nonnull)terminal SWIFT_WARN_UNUSED_RESULT;
/// Consume a line if one is available, returning it as Data.
- (NSData * _Nullable)consumeLineData SWIFT_WARN_UNUSED_RESULT;
/// Consume a line if one is available, returning it as a String.
- (NSString * _Nullable)consumeLineString SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC13FBControlCore18FBControlCoreError")
@interface FBControlCoreError : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)describe:(NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)describe:(NSString * _Nonnull)description;
+ (nonnull instancetype)causedBy:(NSError * _Nullable)cause SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)causedBy:(NSError * _Nullable)cause;
- (BOOL)failBool:(NSError * _Nullable * _Nullable)error;
- (int32_t)failInt:(NSError * _Nullable * _Nullable)error;
- (uint32_t)failUInt:(NSError * _Nullable * _Nullable)error;
- (CGRect)failRect:(NSError * _Nullable * _Nullable)error;
- (id _Nullable)fail:(NSError * _Nullable * _Nullable)error;
- (FBFuture<id> * _Nonnull)failFuture SWIFT_WARN_UNUSED_RESULT;
- (void * _Nullable)failPointer:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)extraInfo:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (nonnull instancetype)recursiveDescription;
- (nonnull instancetype)noRecursiveDescription;
- (nonnull instancetype)inDomain:(NSString * _Nonnull)domain;
- (nonnull instancetype)code:(NSInteger)code;
- (NSError * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface FBControlCoreError (SWIFT_EXTENSION(FBControlCore))
+ (NSError * _Nonnull)errorForDescription:(NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)failWithErrorMessage:(NSString * _Nonnull)errorMessage errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)failWithError:(NSError * _Nonnull)failureCause errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)failWithError:(NSError * _Nonnull)failureCause description:(NSString * _Nonnull)description errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)failBoolWithErrorMessage:(NSString * _Nonnull)errorMessage errorOut:(NSError * _Nullable * _Nullable)errorOut SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)failBoolWithError:(NSError * _Nonnull)failureCause errorOut:(NSError * _Nullable * _Nullable)errorOut;
+ (BOOL)failBoolWithError:(NSError * _Nonnull)failureCause description:(NSString * _Nonnull)description errorOut:(NSError * _Nullable * _Nullable)errorOut;
+ (FBFuture<id> * _Nonnull)failFutureWithError:(NSError * _Nonnull)error SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("FBControlCoreGlobalConfiguration")
@interface FBControlCoreGlobalConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval fastTimeout;)
+ (NSTimeInterval)fastTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval regularTimeout;)
+ (NSTimeInterval)regularTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval slowTimeout;)
+ (NSTimeInterval)slowTimeout SWIFT_WARN_UNUSED_RESULT;
/// The logger used wherever a nullable logger parameter is passed as nil.
/// By default it writes only to os_log (subsystem <code>com.facebook.fbcontrolcore</code>) at info level, so
/// in a process without a terminal nothing reaches stderr and diagnostics are only visible via
/// <code>log stream --predicate 'subsystem == "com.facebook.fbcontrolcore"'</code>.
/// <code>FBCONTROLCORE_LOGGING</code> mirrors output to stderr; <code>FBCONTROLCORE_DEBUG_LOGGING</code> raises the level to debug.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id <FBControlCoreLogger> _Nonnull defaultLogger;)
+ (id <FBControlCoreLogger> _Nonnull)defaultLogger SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultLogger:(id <FBControlCoreLogger> _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL confirmCodesignaturesAreValid;)
+ (BOOL)confirmCodesignaturesAreValid SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Internal forwarding protocol used by FBDataBuffer implementations.
SWIFT_PROTOCOL("_TtP13FBControlCore22FBDataBuffer_Forwarder_")
@protocol FBDataBuffer_Forwarder <NSObject>
- (void)run:(id <FBConsumableBuffer> _Nonnull)buffer;
@property (nonatomic, readonly, strong) id <FBDataConsumer> _Nonnull consumer;
@end

/// Consumer which consumes the data asynchronously.
SWIFT_PROTOCOL("_TtP13FBControlCore19FBDataConsumerAsync_")
@protocol FBDataConsumerAsync <NSObject>
/// Number of submitted data that has not been consumed yet.
- (NSInteger)unprocessedDataCount SWIFT_WARN_UNUSED_RESULT;
@end

/// Consumer which consumes the data synchronously in the same context as the caller invoking consumeData.
SWIFT_PROTOCOL("_TtP13FBControlCore18FBDataConsumerSync_")
@protocol FBDataConsumerSync <NSObject>
@end

SWIFT_CLASS("_TtC13FBControlCore19FBDataDownloadInput")
@interface FBDataDownloadInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSURLSessionTask;
@interface FBDataDownloadInput (SWIFT_EXTENSION(FBControlCore)) <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
@end

/// A consumer of dispatch_data.
SWIFT_PROTOCOL("_TtP13FBControlCore22FBDispatchDataConsumer_")
@protocol FBDispatchDataConsumer <NSObject>
/// Consumes the provided binary data.
- (void)consumeData:(dispatch_data_t _Nonnull)data;
/// Consumes an end-of-file.
- (void)consumeEndOfFile;
@end

/// A Protocol for defining file reading.
SWIFT_PROTOCOL("_TtP13FBControlCore20FBFileReaderProtocol_")
@protocol FBFileReaderProtocol
/// Starts reading the file.
- (FBFuture<NSNull *> * _Nonnull)startReading;
/// Stops reading the file.
- (FBFuture<NSNumber *> * _Nonnull)stopReading;
/// Waits for the reader to finish reading, backing off to stopping in the event of a timeout.
- (FBFuture<NSNumber *> * _Nonnull)finishedReadingWithTimeout:(NSTimeInterval)timeout;
/// The current state of the file reader.
@property (nonatomic, readonly) FBFileReaderState state;
/// A Future that resolves when the reading of the file handle has no pending operations on the file descriptor.
@property (nonatomic, readonly, strong) FBFuture<NSNumber *> * _Nonnull finishedReading;
@end

SWIFT_CLASS_NAMED("FBFileReader")
@interface FBFileReader : NSObject <FBFileReaderProtocol>
@property (nonatomic, readonly) FBFileReaderState state;
+ (nonnull instancetype)readerWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile consumer:(id <FBDataConsumer> _Nonnull)consumer logger:(id <FBControlCoreLogger> _Nullable)logger SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)dispatchDataReaderWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile consumer:(id <FBDispatchDataConsumer> _Nonnull)consumer logger:(id <FBControlCoreLogger> _Nullable)logger SWIFT_WARN_UNUSED_RESULT;
+ (FBFuture<FBFileReader *> * _Nonnull)readerWithFilePath:(NSString * _Nonnull)filePath consumer:(id <FBDataConsumer> _Nonnull)consumer logger:(id <FBControlCoreLogger> _Nullable)logger SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (FBFuture<NSNull *> * _Nonnull)startReading SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNumber *> * _Nonnull)stopReading SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNumber *> * _Nonnull)finishedReadingWithTimeout:(NSTimeInterval)timeout SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) FBFuture<NSNumber *> * _Nonnull finishedReading;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBFileWriter")
@interface FBFileWriter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <FBDataConsumer> _Nonnull nullWriter;)
+ (id <FBDataConsumer> _Nonnull)nullWriter SWIFT_WARN_UNUSED_RESULT;
+ (FBFuture<id> * _Nonnull)asyncDispatchDataWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nonnull)syncWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nullable)asyncWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile queue:(dispatch_queue_t _Nonnull)queue error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nullable)asyncWriterWithFileDescriptor:(int32_t)fileDescriptor closeOnEndOfFile:(BOOL)closeOnEndOfFile error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (id <FBDataConsumer, FBDataConsumerLifecycle> _Nullable)syncWriterForFilePath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (FBFuture<id> * _Nonnull)asyncWriterForFilePath:(NSString * _Nonnull)filePath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface FBLoggingDataConsumer (SWIFT_EXTENSION(FBControlCore)) <FBDataConsumer>
@end

/// A Consumable buffer that also allows forwarding and notifying.
SWIFT_PROTOCOL("_TtP13FBControlCore17FBNotifyingBuffer_")
@protocol FBNotifyingBuffer <FBConsumableBuffer>
/// Forwards to another data consumer, notifying every time a terminal is passed.
- (BOOL)consume:(id <FBDataConsumer> _Nonnull)consumer onQueue:(dispatch_queue_t _Nullable)queue untilTerminal:(NSData * _Nonnull)terminal error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Notifies when there has been consumption to a terminal.
- (FBFuture<NSData *> * _Nonnull)consumeAndNotifyWhen:(NSData * _Nonnull)terminal SWIFT_WARN_UNUSED_RESULT;
/// Consumes based upon a fixed-length header, that can be parsed.
- (FBFuture<NSData *> * _Nonnull)consumeHeaderLength:(NSUInteger)headerLength derivedLength:(NSUInteger (^ _Nonnull)(NSData * _Nonnull))derivedLength SWIFT_WARN_UNUSED_RESULT;
@end

@interface FBNullDataConsumer (SWIFT_EXTENSION(FBControlCore)) <FBDataConsumer>
@end

/// Parses the pre-macOS 12 plain-text <code>.crash</code> format.
SWIFT_CLASS("_TtC13FBControlCore25FBPlainTextCrashLogParser")
@interface FBPlainTextCrashLogParser : NSObject <FBCrashLogParser>
- (void)parseCrashLogFromString:(NSString * _Nonnull)str executablePathOut:(NSString * _Nonnull * _Nonnull)executablePathOut identifierOut:(NSString * _Nonnull * _Nonnull)identifierOut processNameOut:(NSString * _Nonnull * _Nonnull)processNameOut parentProcessNameOut:(NSString * _Nonnull * _Nonnull)parentProcessNameOut processIdentifierOut:(pid_t * _Nonnull)processIdentifierOut parentProcessIdentifierOut:(pid_t * _Nonnull)parentProcessIdentifierOut dateOut:(NSDate * _Nonnull * _Nonnull)dateOut exceptionDescription:(NSString * _Nonnull * _Nonnull)exceptionDescription crashedThreadDescription:(NSString * _Nonnull * _Nonnull)crashedThreadDescription error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Process Output that can be provided through a file.
SWIFT_PROTOCOL("_TtP13FBControlCore19FBProcessFileOutput_")
@protocol FBProcessFileOutput <NSObject>
/// The File Path to write to.
@property (nonatomic, readonly, copy) NSString * _Nonnull filePath;
/// Should be called just after the file path has been written to.
- (FBFuture<NSNull *> * _Nonnull)startReading SWIFT_WARN_UNUSED_RESULT;
/// Should be called just after the file has stopped being written to.
- (FBFuture<NSNull *> * _Nonnull)stopReading SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("FBProcessInfo")
@interface FBProcessInfo : NSObject <NSCopying>
@property (nonatomic, readonly) pid_t processIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull launchPath;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull arguments;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull environment;
@property (nonatomic, readonly, copy) NSString * _Nonnull processName;
- (nonnull instancetype)initWithProcessIdentifier:(pid_t)processIdentifier launchPath:(NSString * _Nonnull)launchPath arguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBProcessStreamAttachment;
/// A Protocol that wraps the standard stream stdout, stderr, stdin.
SWIFT_PROTOCOL("_TtP13FBControlCore16FBStandardStream_")
@protocol FBStandardStream <NSObject>
/// Attaches to the output, returning an FBProcessStreamAttachment.
- (FBFuture<FBProcessStreamAttachment *> * _Nonnull)attach SWIFT_WARN_UNUSED_RESULT;
/// Tears down the output.
- (FBFuture<NSNull *> * _Nonnull)detach SWIFT_WARN_UNUSED_RESULT;
@end

@interface FBProcessInput<WrappedType> (SWIFT_EXTENSION(FBControlCore)) <FBStandardStream>
@end

/// Process output that can be redirected to a file path or to a data consumer.
SWIFT_PROTOCOL_NAMED("FBProcessOutputProtocol")
@protocol FBProcessOutput <NSObject>
/// Allows the receiver to be written to via a file instead of via a file handle.
- (FBFuture<id <FBProcessFileOutput>> * _Nonnull)providedThroughFile SWIFT_WARN_UNUSED_RESULT;
/// Allows the receiver to be written to via a Data Consumer.
- (FBFuture<id <FBDataConsumer>> * _Nonnull)providedThroughConsumer SWIFT_WARN_UNUSED_RESULT;
@end

@interface FBProcessOutput<WrappedType> (SWIFT_EXTENSION(FBControlCore)) <FBProcessOutput, FBStandardStream>
@end

@class FBProcessIOAttachment;
@class FBProcessSpawnConfiguration;
SWIFT_CLASS_NAMED("FBProcessSpawnCommandHelpers")
@interface FBProcessSpawnCommandHelpers : NSObject
+ (void)resolveProcessFinishedWithStatLoc:(int32_t)statLoc inTeardownOfIOAttachment:(FBProcessIOAttachment * _Nonnull)attachment statLocFuture:(FBMutableFuture<NSNumber *> * _Nonnull)statLocFuture exitCodeFuture:(FBMutableFuture<NSNumber *> * _Nonnull)exitCodeFuture signalFuture:(FBMutableFuture<NSNumber *> * _Nonnull)signalFuture processIdentifier:(pid_t)processIdentifier configuration:(FBProcessSpawnConfiguration * _Nonnull)configuration queue:(dispatch_queue_t _Nonnull)queue logger:(id <FBControlCoreLogger> _Nullable)logger;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_ENUM_FWD_DECL(NSUInteger, FBProcessSpawnMode)
SWIFT_CLASS_NAMED("FBProcessSpawnConfiguration")
@interface FBProcessSpawnConfiguration : FBProcessLaunchConfiguration
@property (nonatomic, readonly, copy) NSString * _Nonnull launchPath;
@property (nonatomic, readonly) enum FBProcessSpawnMode mode;
@property (nonatomic, readonly, copy) NSString * _Nonnull processName;
- (nonnull instancetype)initWithLaunchPath:(NSString * _Nonnull)launchPath arguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io mode:(enum FBProcessSpawnMode)mode OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)initWithArguments:(NSArray<NSString *> * _Nonnull)arguments environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment io:(FBProcessIO<id, id, id> * _Nonnull)io SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM_NAMED(NSUInteger, FBProcessSpawnMode, "FBProcessSpawnMode", open) {
  FBProcessSpawnModeDefault = 0,
  FBProcessSpawnModePosixSpawn = 1,
  FBProcessSpawnModeLaunchd = 2,
};

@class FBSocketServer;
/// The Delegate for the Server.
SWIFT_PROTOCOL("_TtP13FBControlCore22FBSocketServerDelegate_")
@protocol FBSocketServerDelegate <NSObject>
/// Called when the socket server has a new client connected.
/// The File Descriptor will not be automatically be closed, so it’s up to implementors to ensure that this happens so file descriptors do not leak.
/// If you wish to reject the connection, close the file handle immediately.
/// \param server the socket server.
///
/// \param address the IP Address of the connected client.
///
/// \param fileDescriptor the file descriptor of the connected socket.
///
- (void)socketServer:(FBSocketServer * _Nonnull)server clientConnected:(struct in6_addr)address fileDescriptor:(int32_t)fileDescriptor;
/// The Queue on which the Delegate will be called.
/// This may be a serial or a concurrent queue.
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull queue;
@end

/// Provides information about the state of a stream.
SWIFT_PROTOCOL("_TtP13FBControlCore24FBStandardStreamTransfer_")
@protocol FBStandardStreamTransfer <NSObject>
/// The number of bytes transferred.
@property (nonatomic, readonly) NSInteger bytesTransferred;
/// An error, if any has occurred in the streaming of data to the input.
@property (nonatomic, readonly) NSError * _Nullable streamError;
@end

@class AVCaptureFileOutput;
@class NSURL;
@class AVCaptureConnection;
SWIFT_CLASS("_TtC13FBControlCore17FBVideoFileWriter")
@interface FBVideoFileWriter : NSObject <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didStartRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didPauseRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output willFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didResumeRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBWeakFramework")
@interface FBWeakFramework : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
+ (FBWeakFramework * _Nonnull)xcodeFrameworkWithRelativePath:(NSString * _Nonnull)relativePath requiredClassNames:(NSArray<NSString *> * _Nonnull)requiredClassNames SWIFT_WARN_UNUSED_RESULT;
+ (FBWeakFramework * _Nonnull)frameworkWithPath:(NSString * _Nonnull)absolutePath requiredClassNames:(NSArray<NSString *> * _Nonnull)requiredClassNames rootPermitted:(BOOL)rootPermitted SWIFT_WARN_UNUSED_RESULT;
/// A nil logger loads silently.
- (BOOL)loadWithLogger:(id <FBControlCoreLogger> _Nullable)logger error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface FBWeakFramework (SWIFT_EXTENSION(FBControlCore))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull CoreSimulator;)
+ (FBWeakFramework * _Nonnull)CoreSimulator SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull SimulatorKit;)
+ (FBWeakFramework * _Nonnull)SimulatorKit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull DTXConnectionServices;)
+ (FBWeakFramework * _Nonnull)DTXConnectionServices SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull XCTDaemonControl;)
+ (FBWeakFramework * _Nonnull)XCTDaemonControl SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull XCUIAutomation;)
+ (FBWeakFramework * _Nonnull)XCUIAutomation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull XCTest;)
+ (FBWeakFramework * _Nonnull)XCTest SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull MobileDevice;)
+ (FBWeakFramework * _Nonnull)MobileDevice SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FBWeakFramework * _Nonnull AccessibilityPlatformTranslation;)
+ (FBWeakFramework * _Nonnull)AccessibilityPlatformTranslation SWIFT_WARN_UNUSED_RESULT;
@end

@class NSDecimalNumber;
@class NSNumberFormatter;
SWIFT_CLASS_NAMED("FBXcodeConfiguration")
@interface FBXcodeConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull developerDirectory;)
+ (NSString * _Nonnull)developerDirectory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull contentsDirectory;)
+ (NSString * _Nonnull)contentsDirectory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDecimalNumber * _Nonnull xcodeVersionNumber;)
+ (NSDecimalNumber * _Nonnull)xcodeVersionNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSOperatingSystemVersion xcodeVersion;)
+ (NSOperatingSystemVersion)xcodeVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDecimalNumber * _Nonnull iosSDKVersionNumber;)
+ (NSDecimalNumber * _Nonnull)iosSDKVersionNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSNumberFormatter * _Nonnull iosSDKVersionNumberFormatter;)
+ (NSNumberFormatter * _Nonnull)iosSDKVersionNumberFormatter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull iosSDKVersion;)
+ (NSString * _Nonnull)iosSDKVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isXcode12OrGreater;)
+ (BOOL)isXcode12OrGreater SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isXcode12_5OrGreater;)
+ (BOOL)isXcode12_5OrGreater SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)description SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("FBiOSTargetConfiguration")
@interface FBiOSTargetConfiguration : NSObject
+ (NSSet<FBArchitecture> * _Nonnull)baseArchsToCompatibleArch:(NSArray<FBArchitecture> * _Nonnull)architectures SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSPredicate (SWIFT_EXTENSION(FBControlCore))
+ (NSPredicate * _Nonnull)notNullPredicate SWIFT_WARN_UNUSED_RESULT;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
